version: '3.8'
services:
  gateway:
    build: gateway/
    container_name: gateway
    image: "gateway-image"
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/
    ports:
      - "9090:9090"
    container_name: server
    image: "server-image"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share_it_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=item

  db:
    image: postgres:13.7
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share_it_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=item